const Photo = {
  account_icon: require("../Images/account_icon.png"),
  iconfinder_1: require("../Images/iconfinder_1.png"),
  Chip_Card_1: require("../Images/Chip_Card_1.png"),
  credit_card_icon: require("../Images/credit-card_icon.png"),
  dashboard_icon: require("../Images/dashboard_icon.png"),
  investment_icon: require("../Images/investment_icon.png"),
  loan_icon: require("../Images/loan_icon.png"),
  myPrivileges_icon: require("../Images/myPrivileges_icon.png"),
  service_icon: require("../Images/service_icon.png"),
  setting_icon: require("../Images/setting_icon.png"),
  transaction_icon: require("../Images/transaction_icon.png"),
  accounts_blue_icon: require("../ImagesBlue/accounts_blue_icon.png"),
  dashboard_blue_icon: require("../ImagesBlue/dashboard_blue_icon.png"),
  transaction_blue_icon: require("../ImagesBlue/transaction_blue_icon.png"),
  investment_blue_icon: require("../ImagesBlue/investment_blue_icon.png"),
  credit_card_blue_icon: require("../ImagesBlue/credit_card_blue_icon.png"),
  loan_blue_icon: require("../ImagesBlue/loan_blue_icon.png"),
  services_blue_icon: require("../ImagesBlue/services_blue_icon.png"),
  setting_blue_icon: require("../ImagesBlue/setting_blue_icon.png"),
  profile_picture: require("../Images/profile_picture.png"),
  bell_icon: require("../Images/bell_icon.png"),
  Setting_Symbol: require("../Images/Setting_Symbol.png"),
  magnifyglass: require("../SVG/magnifyglass.svg"),
  MenuBar: require("../Images/MenuBar.png"),
  cross: require("../Images/cross.png"),
};

export default Photo;
